### ISSUE TITLE
nuxt/nuxtjs.org への移行

### ISSUE THREAD

**Issue by aytdm** [vuejs-jp/ja.nuxtjs.org#22]
Nuxt.js の ドキュメントが置かれているレポジトリが `nuxt/docs` から `nuxt/nuxtjs.org` に変更されました。
移行にあたり今後のタスクを issue 化します。

@inouetakuya @53able 先日話したことを issue 化しました。不足があれば加筆いただけると助かります

### TODO

- [x] 新しいドキュメントのレポジトリをfork
  - https://github.com/vuejs-jp/ja.nuxtjs.org
- [x] バッチの修正
  - https://github.com/vuejs-jp/sharin/issues/23
  - https://github.com/vuejs-jp/sharin/pull/24
- [x] `nuxt/nuxtjs.org` で権限を付与してもらえないかお願いする
  - https://github.com/nuxt/nuxtjs.org/issues/544#issuecomment-679190218 依頼中。
- [x] wiki の作成
  - https://github.com/vuejs-jp/ja.docs.nuxtjs/wiki をベースにする
- [x] home のリンク修正
  - https://github.com/vuejs-jp/home/pull/59
- [x] ~[nuxt/docs に残っている issue](https://github.com/vuejs-jp/ja.docs.nuxtjs/issues) を片付ける~
  - blog は持ち越す。それ以外は保留（`guides` 翻訳後に `guide`、`api` は削除されるそうなので訳さない）
    - 残存 issue はクローズ。必要あれば新しく issue をたてる
- [x] `vuejs-jp/ja.nuxtjs.org` の運用
  - `guides` を優先的に翻訳していく
  - 翻訳が必要な `guides` のファイル一覧：https://github.com/nuxt/nuxtjs.org/issues/544#issue-684667241
- [ ] Slack 連携
  - `guides` の翻訳があらかた落ち着いた後…

**Comment by aytdm** [comment]
> https://github.com/nuxt/nuxtjs.org/issues/544#issuecomment-679151041
The guide and api section will soon be removed once the guides section is translated. Examples, faq and resources will be moved to a new section and will be improved. We are working on this at present but it will be a while before released. Guides would be the best place to start in my opinion as this is the new en version.

とのことなので、`guides` を優先的に訳すのがよさそうです。

**Comment by aytdm** [comment]
### 概要

`guides` で対応が必要なファイル一覧（https://github.com/nuxt/nuxtjs.org/issues/544#issue-684667241 より引用）

### ファイル一覧

**i18n configuration**

* [ ]   i18n file
* [ ]   i18n block on nuxt.config

📝 **guides -> components glossary**

* [ ]   pages-fetch.md
* [ ]   pages-head.md
* [ ]   pages-key.md
* [ ]   pages-layout.md
* [ ]   pages-loading.md
* [ ]   pages-middleware.md
* [ ]   pages-scrolltotop.md
* [ ]   pages-transition.md
* [ ]   pages-validate.md
* [ ]   pages-watchquery.md

📝 **guides -> concepts**

* [ ]   context-helpers.md
* [ ]   nuxt-lifecycle.md
* [ ]   server-side-rendering.md
* [ ]   static-site-generation.md
* [ ]   views.md

📝 **guides -> configuration glossary**

* [ ]  configuration-build.md
* [ ]   configuration-generate.md
* [ ]   configuration-render.md
* [ ]   configuration-server.md
* [ ]   configuration-telemetry.md
* [ ]   configuration-router.md
* [ ]   configuration-server-middleware.md
* [ ]   configuration-transition.md
* [ ]   configuration-builddir.md
* [ ]   configuration-cli.md
* [ ]   configuration-components.md
* [ ]   configuration-css.md
* [ ]   configuration-dev.md
* [ ]   configuration-dir.md
* [ ]   configuration-env.md
* [ ]   configuration-extend-plugins.md
* [ ]   configuration-global-name.md
* [ ]   configuration-head.md
* [ ]   configuration-hooks.md
* [ ]   configuration-ignore.md
* [ ]   configuration-loading.md
* [ ]   configuration-loading-indicator.md
* [ ]   configuration-mode.md
* [ ]   configuration-modern.md
* [ ]   configuration-modules.md
* [ ]   configuration-modulesdir.md
* [ ]   configuration-plugins.md
* [ ]   configuration-rootdir.md
* [ ]   configuration-runtime-config.md
* [ ]   configuration-srcdir.md
* [ ]   configuration-target.md
* [ ]   configuration-vue-config.md
* [ ]   configuration-watch.md
* [ ]   configuration-watchers.md

📝 **guides -> directory structure**

* [ ]   assets.md
* [ ]   components.md
* [ ]   content.md
* [ ]   dist.md
* [ ]   layouts.md
* [ ]   middleware.md
* [ ]   modules.md
* [ ]   nuxt.md
* [ ]   nuxt-config.md
* [ ]   pages.md
* [ ]   plugins.md
* [ ]   static.md
* [ ]   store.md

📝 **guides -> features**

* [ ]   configuration.md
* [ ]   data-fetching.md
* [ ]   deployment-targets.md
* [ ]   file-system-routing.md
* [ ]   live-preview.md
* [ ]   loading.md
* [ ]   meta-tags-seo.md
* [ ]   nuxt-components.md
* [ ]   rendering-modes.md
* [ ]   transitions.md

📝 **guides -> get-started**

* [ ]   conclusion.md
* [ ]   directory-structure.md
* [ ]   installation.md
* [ ]   routing.md
* [ ]   upgrading.md

📝 **guides -> internals glossary**

* [ ]   $nuxt.md
* [ ]   context.md
* [ ]   internals.md
* [ ]   internals-builder.md
* [ ]   internals-generator.md
* [ ]   internals-module-container.md
* [ ]   internals-nuxt.md
* [ ]   internals-renderer.md
* [ ]   nuxt.md
* [ ]   nuxt-render.md
* [ ]   nuxt-render-and-get-window.md
* [ ]   nuxt-render-route.md

**Comment by aytdm** [comment]
`guides/get-started` のファイル一式着手しています

@szk18 ウォッチしてくださっているのでメンションしちゃいます。よければ `guides` の翻訳をして一緒にしていただけないでしょうか？どれか 1 ファイルだけでもご協力いただけるととても助かります。
承認周りやフローが整っていないので、場当たり的な対応が多々あるかもしれない:bow:ですがもしよければぜひ :blush:

**Comment by 53able** [comment]
`guides -> configuration glossary` ファイル一式に手を出していきます。
量が多いので、ご一緒にしていただく方がいても大歓迎でございます😊

 @aytdm

**Comment by szk18** [comment]
@aytdm 
こんにちは！ぜひ協力したいです！
いろいろ相談させてもらうと思いますが、よろしくお願いします🙏

早速ですが `guides -> features` から手をつけてみます💪

**Comment by aytdm** [comment]
わ、ありがとうございます！🙌 よろしくお願いします🙏 何かあればいつでも聞いてください

**Comment by aytdm** [comment]
> https://github.com/nuxt/nuxtjs.org/issues/544#issuecomment-682679694
> 
> Until then feel free to just work away and add me as a reviewer when ready to merge.

とのことなので、これまで通りPR作成→レビュー依頼→完了したら debbie さんをレビュワーに追加してマージ依頼する流れで進められたらと思います。また、PRのタイトルに `docs(ja):` など日本語訳とわかるようにプレフィクスをつけてもらえると助かりますmm

**Comment by aytdm** [comment]
@inouetakuya @53able レビューをお願いしたいんですが難しいでしょうか？忙しいとか状況教えてもらえると助かります:pray:

**Comment by inouetakuya** [comment]
@aytdm 

全然アクションできてなくて、numa さんが抱え込む状況になっていて、ごめんなさい！！ 🙇‍♂️ 

そして（きっと勇気を出して）コメントしてくださって、ありがとうございます！！

状況としては、

- 時間的な余裕はある
- 精神的に余裕がない日が数か月続いていた -> 少し落ち着いてきた
- やろうやろうとは思っていた

で、numa さんのコメントで目が覚めたので、今日からレビューやっていきます！！

**Comment by aytdm** [comment]
ありがとうございます。すみませんがよろしくお願いしますmm
（忙しいならメンションしないでおこうかな、とか進め方を変えようかな、と思っていました）

**Comment by inouetakuya** [comment]
`guides -> components glossary` を翻訳していきます〜

**Comment by inouetakuya** [comment]
@aytdm 

確認なのですが、

> home のリンク修正

これって https://github.com/vuejs-jp/home/blame/master/README.md#L38 の修正という理解で合っていますか？

**Comment by aytdm** [comment]
> これって https://github.com/vuejs-jp/home/blame/master/README.md#L38 の修正という理解で合っていますか？

Readme とサイト中のリンクも修正しようと思っていました（README へのリンクより、wiki にリンクしたほうがいいかなと思ったので）。週末までに私の方で PR 作ります

**Comment by inouetakuya** [comment]
なるほど、ありがとうございます！お願いします！
